Repository DailyGreen/Tiler-Client, pull requests merged in 2021-02, with the labels that each got.

#98 [수정] 터렛 버그수정 [병합] #97
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Unit/Desert/Desert_Worker.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/Scripts/Unit/Sea/Sea_Worker.cs
  Assets/Scripts/Unit/Unit.cs
  Assets/Scripts/Unit/Worker.cs
  Assets/Sprites/hexagon-pack/food.png
  Assets/Sprites/hexagon-pack/food.png.meta
Labels: 병합, 수정

#101 [수정] 터렛 공격 애니메이션 수정
  Assets/Animation/Built/Turret/Attack.anim
  Assets/Prefabs/Built/Turret.prefab
Labels: 수정

#102 [수정] 맵 변경
  Assets/Resources/mapinfo.txt
Labels: 수정

#105 [병합] [추가] #103, #104, 턴 넘기기 버튼 추가
  Assets/Animation/InGame/TurnSkip.controller
  Assets/Animation/InGame/TurnSkip.controller.meta
  Assets/Animation/Unit/Desert/DesertSoldier_2/Attack.anim
  Assets/Animation/Unit/Desert/DesertSoldier_2/Create.anim
  Assets/Animation/Unit/Desert/Desertwitch_1/Running.anim
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/MillitaryBase.cs
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Unit/Desert/Desert_Worker.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/Scripts/Unit/Sea/Sea_Worker.cs
  Assets/Scripts/Unit/Unit.cs
Labels: 병합, 수정, 추가

#106 [수정] 게임 시작 캔버스 수정
  Assets/Scenes/InGame.unity
Labels: 수정

#107 [추가] 마우스 오버 UI 설명 기능 추가
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scenes/InGame.unity
  Assets/Scenes/Lobby.unity
  Assets/Scripts/InGame/ToolTip.cs
  Assets/Scripts/InGame/ToolTip.cs.meta
  Assets/Scripts/InGame/Window.cs
  Assets/Scripts/InGame/Window.cs.meta
  Assets/Scripts/Manager/GameMng.cs
  Assets/Sprites/Emote/emote_food.png
  Assets/Sprites/UI/github-11-xxl.png
  Assets/Sprites/UI/github-11-xxl.png.meta
  Assets/dailygreen.png
  Assets/dailygreen.png.meta
Labels: 추가

#108 [수정] 터렛 공격할때 부셔지면 오류나는버그 수정
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scripts/Manager/GameMng.cs
Labels: 수정
