Repository DailyGreen/Tiler-Client, pull requests merged in 2021-01, with the labels that each got.

#10 [추가]플레이어 이동, 행동 인터페이스, 건설
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Built.cs
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/Farm.cs.meta
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/Built/Mine.cs.meta
  Assets/Scripts/InGame/MainCameraScrp.cs
  Assets/Scripts/InGame/RangeScrp.cs
  Assets/Scripts/InGame/RangeScrp.cs.meta
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Object.cs
  Assets/Scripts/Tile/Tile.cs
  Assets/Scripts/Unit/Unit.cs
  Assets/Scripts/Unit/Worker.cs
Labels: 병합

#11 [추가] 건물 생성 구현
  .vsconfig
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Built.cs
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/InGame/MainCameraScrp.cs
  Assets/Scripts/InGame/RangeScrp.cs
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Manager/UnitMng.cs.meta
  Assets/Scripts/Unit/Worker.cs
  ProjectSettings/TimelineSettings.asset
Labels: 추가

#14 [추가] 성 오브젝트 기능 구현
  Assets/Prefabs/Built/Castle.prefab
  Assets/Prefabs/Built/Castle.prefab.meta
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Castle.cs
  Assets/Scripts/Built/Castle.cs.meta
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/InGame/MainCamera.cs
  Assets/Scripts/InGame/RangeControl.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/BuiltMng.cs.meta
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Tile/HexTileCreate.cs
  Assets/Scripts/Tile/Tile.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/mapinfo.txt
Labels: 추가

#21 [추가] 종족, 색상 변경 기능
  Assets/Animation/LobbyAni/ForestTribeBT.controller
  Assets/Animation/LobbyAni/ForestTribeBT.controller.meta
  Assets/Animation/LobbyAni/SeaTribeBT.controller
  Assets/Animation/LobbyAni/SeaTribeBT.controller.meta
  Assets/Animation/LobbyAni/VillageTribeBT.controller
  Assets/Animation/LobbyAni/VillageTribeBT.controller.meta
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Built/Turret.prefab
  Assets/Scenes/InGame.unity
  Assets/Scenes/Lobby.unity
  Assets/Scripts/Built/Castle.cs
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/InGame/MainCamera.cs
  Assets/Scripts/InGame/RangeControl.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/RoomMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Sprites/Tribe.meta
  Assets/Sprites/Tribe/Forest.png
  Assets/Sprites/Tribe/Forest.png.meta
  Assets/Sprites/Tribe/Sea.png
  Assets/Sprites/Tribe/Sea.png.meta
  Assets/Sprites/Tribe/Village.png
  Assets/Sprites/Tribe/Village.png.meta
Labels: 병합, 추가

#28 [추가] 유닛 생성 및 이동, 건물 생성 서버와 연동
  Assets/Animation/Built/Farm/idle.anim
  Assets/Animation/Built/Mine/idle.anim
  Assets/Animation/Unit/Forest/ForestWorker/ForestWorker.controller
  Assets/Animation/Unit/Forest/ForestWorker/create.anim
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Built/AirDrop.prefab
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Tile/HexTileCreate.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_0.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_1.cs
  Assets/Scripts/Unit/Unit.cs
  Assets/Scripts/Unit/Worker.cs
Labels: 병합, 추가

#34 [병합]#33
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scripts/Built/Castle.cs
  Assets/Scripts/InGame/RangeControl.cs
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Tile/HexTileCreate.cs
  Assets/Scripts/Tile/Tile.cs
  Assets/Scripts/Unit/Worker.cs
Labels: 병합

#49 [병합] DailyGreen #46, #47, #48 병합
  Assets/Animation/Built/Farm/idle.anim
  Assets/Animation/Built/Military_Base.meta
  Assets/Animation/Built/Military_Base/Create.anim
  Assets/Animation/Built/Military_Base/Create.anim.meta
  Assets/Animation/Built/Military_Base/Idle.anim
  Assets/Animation/Built/Military_Base/Idle.anim.meta
  Assets/Animation/Built/Military_Base/Military_Base.controller
  Assets/Animation/Built/Military_Base/Military_Base.controller.meta
  Assets/Animation/Built/Mine/Mine.controller
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Built/Military_Base.prefab
  Assets/Prefabs/Built/Mine.prefab
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/MillitaryBase.cs
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/DynamicObject.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/RoomMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_0.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_1.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_0.cs
  Assets/Scripts/Unit/Sea/Sea_Worker.cs
Labels: 병합

#57 [병합] #56 병합, 건물 생성, 병력 생성 중 오브젝트 행동 불능 기능 추가
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Built/Turret.prefab
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Castle.cs
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/MillitaryBase.cs
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/DynamicObject.cs
  Assets/Scripts/InGame/RangeControl.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/Enum.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_0.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_1.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_0.cs
  Assets/Scripts/Unit/Sea/Sea_Worker.cs
  Assets/Scripts/Unit/Unit.cs
  Assets/Sprites/hexagon-pack/turret_small_head.png
  Assets/Sprites/hexagon-pack/turret_small_head.png.meta
Labels: 병합, 추가

#67 [병합] #66
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Range.meta
  Assets/Prefabs/Range/AttackRange.prefab
  Assets/Prefabs/Range/AttackRange.prefab.meta
  Assets/Prefabs/Range/MoveRange.prefab
  Assets/Prefabs/Range/MoveRange.prefab.meta
  Assets/Prefabs/Range/SelectRange.prefab
  Assets/Prefabs/Range/SelectRange.prefab.meta
  Assets/Scenes/InGame.unity
  Assets/Scenes/Lobby.unity
  Assets/Scripts/Built/Castle.cs
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/InGame/MainCamera.cs
  Assets/Scripts/InGame/RangeControl.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/NetworkMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Tile/HexTileCreate.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_0.cs
  Assets/Sprites/hexagon-pack/neon_hexa.png
  Assets/Sprites/hexagon-pack/neon_hexa.png.meta
Labels: 병합, 수정, 추가

#68 [수정] tilecode 초기화버그 수정 범위 버그 수정
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scenes/InGame.unity
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Tile/HexTileCreate.cs
Labels: 수정

#73 [수정] 유닛 생성중 건물 파괴시 게임이 멈추던 버그 수정
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scenes/InGame.unity
  Assets/Scenes/asdfasdf.unity
  Assets/Scenes/asdfasdf.unity.meta
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Unit/Unit.cs
Labels: 병합, 수정

#81 [수정] 메인바, 오브젝트 메세지 버그 수정
  Assets/Animation/Unit/Forest/ForestSoldier_2/Attacking.anim
  Assets/Animation/Unit/Forest/ForestSoldier_2/Chara_05.controller
  Assets/Animation/Unit/Forest/ForestSoldier_2/Create.anim
  Assets/Animation/Unit/Forest/ForestSoldier_2/Dying.anim
  Assets/Animation/Unit/Forest/ForestSoldier_2/ForestSoldier_2.controller
  Assets/Animation/Unit/Forest/ForestSoldier_2/ForestSoldier_2.controller.meta
  Assets/Animation/Unit/Forest/ForestSoldier_2/Running.anim
  Assets/Animation/Unit/Forest/ForestWitch_0/ForestWitch_0.controller
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Tile/grass_05.prefab
  Assets/Scenes/InGame.unity
  Assets/Scripts/Built/Castle.cs
  Assets/Scripts/Built/Farm.cs
  Assets/Scripts/Built/MillitaryBase.cs
  Assets/Scripts/Built/Mine.cs
  Assets/Scripts/Built/Turret.cs
  Assets/Scripts/InGame/MainCamera.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Tile/HexTileCreate.cs
  Assets/Scripts/Unit/Desert/Desert_Soldier_0.cs
  Assets/Scripts/Unit/Desert/Desert_Soldier_1.cs
  Assets/Scripts/Unit/Desert/Desert_Soldier_2.cs
  Assets/Scripts/Unit/Desert/Desert_Witch_0.cs
  Assets/Scripts/Unit/Desert/Desert_Witch_1.cs
  Assets/Scripts/Unit/Desert/Desert_Worker.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_0.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_1.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_2.cs
  Assets/Scripts/Unit/Forest/Forest_Witch_0.cs
  Assets/Scripts/Unit/Forest/Forest_Witch_1.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_0.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_1.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_2.cs
  Assets/Scripts/Unit/Sea/Sea_Witch_0.cs
  Assets/Scripts/Unit/Sea/Sea_Witch_1.cs
  Assets/Scripts/Unit/Sea/Sea_Worker.cs
  Assets/Scripts/Unit/Unit.cs
  Assets/Wide Room.prefab
Labels: 병합, 수정

#82 [수정] 유닛 생성 코스트 종족값에 따라 다르게 수정
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Unit/Desert/Desert_Soldier_0.cs
  Assets/Scripts/Unit/Desert/Desert_Soldier_1.cs
  Assets/Scripts/Unit/Desert/Desert_Soldier_2.cs
  Assets/Scripts/Unit/Desert/Desert_Witch_0.cs
  Assets/Scripts/Unit/Desert/Desert_Witch_1.cs
  Assets/Scripts/Unit/Desert/Desert_Worker.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_0.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_1.cs
  Assets/Scripts/Unit/Forest/Forest_Soldier_2.cs
  Assets/Scripts/Unit/Forest/Forest_Witch_0.cs
  Assets/Scripts/Unit/Forest/Forest_Witch_1.cs
  Assets/Scripts/Unit/Forest/Forest_Worker.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_0.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_1.cs
  Assets/Scripts/Unit/Sea/Sea_Soldier_2.cs
  Assets/Scripts/Unit/Sea/Sea_Witch_0.cs
  Assets/Scripts/Unit/Sea/Sea_Witch_1.cs
  Assets/Scripts/Unit/Sea/Sea_Worker.cs
Labels: 병합, 수정

#86 [수정] 이모트 애니메이션 수정
  Assets/Animation/Unit/Sea/SeaWitch_0/Attacking.anim
  Assets/Animation/Unit/Sea/SeaWitch_0/Create.anim
  Assets/Animation/Unit/Sea/SeaWitch_0/Dying.anim
  Assets/Animation/Unit/Sea/SeaWitch_0/Idle.anim
  Assets/Animation/Unit/Sea/SeaWitch_0/Running.anim
  Assets/Animation/Unit/Sea/SeaWitch_0/Spawning.anim
  Assets/Prefabs/Unit/Desert/DesertWorker.prefab
  Assets/Prefabs/Unit/Sea/SeaWorker.prefab
Labels: 수정

#87 [수정] 애니메이션 최종 수정
  Assets/Animation/Unit/Desert/DesertSoldier_1/Attack.anim
  Assets/Animation/Unit/Desert/DesertSoldier_1/Create.anim
  Assets/Animation/Unit/Desert/DesertSoldier_1/Die.anim
  Assets/Animation/Unit/Desert/DesertSoldier_1/Idle.anim
  Assets/Animation/Unit/Desert/DesertSoldier_1/Runnig.anim
  Assets/Animation/Unit/Desert/DesertSoldier_1/Spawning.anim
  Assets/Animation/Unit/Desert/DesertWorker/Die.anim
  Assets/Animation/Unit/Desert/DesertWorker/ReadyToWork.anim
  Assets/Animation/Unit/Desert/DesertWorker/Running.anim
  Assets/Animation/Unit/Desert/DesertWorker/Spawning.anim
  Assets/Animation/Unit/Desert/DesertWorker/create.anim
  Assets/Animation/Unit/Desert/DesertWorker/idle.anim
  Assets/Animation/Unit/Desert/Desertwitch_1/Attack.anim
  Assets/Animation/Unit/Desert/Desertwitch_1/Create.anim
  Assets/Animation/Unit/Forest/ForestSoldier_0/Die.anim
  Assets/Animation/Unit/Forest/ForestSoldier_2/Running.anim
  Assets/Animation/Unit/Sea/SeaSoldier_1/Attacking.anim
  Assets/Animation/Unit/Sea/SeaSoldier_1/Create.anim
  Assets/Animation/Unit/Sea/SeaSoldier_1/Dying.anim
  Assets/Animation/Unit/Sea/SeaSoldier_1/Idle.anim
  Assets/Animation/Unit/Sea/SeaSoldier_1/Running.anim
  Assets/Animation/Unit/Sea/SeaSoldier_1/Spawning.anim
  Assets/Animation/Unit/Sea/SeaSoldier_2/Attacking.anim
  Assets/Animation/Unit/Sea/SeaSoldier_2/Create.anim
  Assets/Animation/Unit/Sea/SeaSoldier_2/Dying.anim
  Assets/Animation/Unit/Sea/SeaSoldier_2/Idle.anim
  Assets/Animation/Unit/Sea/SeaSoldier_2/Running.anim
  Assets/Animation/Unit/Sea/SeaSoldier_2/Spawning.anim
  Assets/Animation/Unit/Sea/Sea_Witch_1/Attack.anim
  Assets/Animation/Unit/Sea/Sea_Witch_1/Create.anim
  Assets/Animation/Unit/Sea/Sea_Witch_1/Dying.anim
  Assets/Animation/Unit/Sea/Sea_Witch_1/Idle.anim
  Assets/Animation/Unit/Sea/Sea_Witch_1/Running.anim
  Assets/Animation/Unit/Sea/Sea_Witch_1/Spawning.anim
  Assets/Prefabs/Unit/Desert/DesertSoldier_1.prefab
  Assets/Prefabs/Unit/Desert/DesertSoldier_2.prefab
  Assets/Prefabs/Unit/Desert/DesertWitch_0.prefab
  Assets/Prefabs/Unit/Desert/DesertWitch_1.prefab
  Assets/Prefabs/Unit/Desert/DesertWorker.prefab
Labels: 병합, 수정

#88 [수정] 애니메이션 최종 수정, 버튼 폰트 수정
  Assets/Animation/Unit/Desert/Desertwitch_0/Spawning.anim
  Assets/Animation/Unit/Sea/SeaWitch_0/Running.anim
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Prefabs/Unit/Desert/DesertWitch_1.prefab
  Assets/Scenes/InGame.unity
  Assets/Scripts/Manager/UnitMng.cs
Labels: 수정

#92 [수정] 버그 수정
  Assets/Lomenu UI/Materials/Dissolve/Hexart_DECG.mat
  Assets/Scenes/InGame.unity
  Assets/Scripts/InGame/MainCamera.cs
  Assets/Scripts/Manager/BuiltMng.cs
  Assets/Scripts/Manager/GameMng.cs
  Assets/Scripts/Manager/UnitMng.cs
  Assets/Scripts/Tile/HexTileCreate.cs
  Assets/Scripts/Unit/Unit.cs
Labels: 병합, 수정
